### PR TITLE
Refactored index.html to HTML5 validated form

### PR DESCRIPTION
**Pull request by jremes-foss**
Hello. 

Just a quick PR: index.html was not HTML5 compatible. W3C Validator gave the following error message. 

Line 173, Column 73: The frameborder attribute on the iframe element is obsolete.

I removed the frameborder attribute and replaced it with CSS. 

This file is now HTML5 compatible - did the pre/post change testing, it works as intended after re-factoring. 

Thanks.

### CODE REVIEW

**Comment by timkeane** [comment]
I was aware of that validation error, but never fixed it over concern for rendering in ie8 which unfortunately has to be supported for NYC DOE internal users.  I use the [Validity Extension for Chrome](https://github.com/renyard/validity) to check. I'll look into how/if removing the attribute effects ie8.  In the meantime I think this style rule would be better placed in `upk.css` within `#external-page iframe` line 57.

**Comment by jremes-foss** [comment]
Yes, I noted that there was actually quite a lot CSS in the HTML file. It is part of best practices to put the CSS to separate files. Same goes to JavaScript.

**Comment by timkeane** [comment]
No CSS in the raw HTML of index.html.  The OpenLayers and JQuery Mobile libs definitely set a lot of CSS dynamically though.

**Comment by timkeane** [comment]
When I view in IE 11 set to IE 8 mode with the frameborder attribute removed, the iframe has a 3D border.  I'm not aware of a way to remove the HTML5 validation error while preventing this behavior in IE 8, are you?

**Comment by jremes-foss** [comment]
I can have a look at it, I am sure there is a way.

**Comment by jremes-foss** [comment]
Got possible solution using JavaScript. Still need to test it with my Windows laptop.

**Comment by timkeane** [comment]
I was considering `$("#external-content iframe").attr("frameborder", 0);` in `ie8.js`

**Comment by jremes-foss** [comment]
I have traditional JavaScript solution handy this evening, but jQuery could be even better. Is the ie8.js main JavaScript file controlling the IE8 compatibility?

**Comment by timkeane** [comment]
yes... `ie8.js` is loaded along with `ie8.css` within an `<!--[if lt IE 9]>` comment block in the `<head>` of `index.html`

**Comment by timkeane** [comment]
was able to get DOE to enable CORS eliminating the need for the iframe for the Get in Touch form (info.html).  frameborder attribute now removed from the iframe.

**Comment by jremes-foss** [comment]
Excellent to hear that it's sorted out. Sorry about being a bit inactive, been really busy with work. :)

**Pull request closed without merging**
